### ISSUE TITLE
'ACEStepTransformer2DModel' object has no attribute '_set_gradient_checkpointing'. Did you mean: 'is_gradient_checkpointing'?

### ISSUE THREAD

**Issue by Meliauo** [woct0rdho/ACE-Step#2]
I encountered this error when running trainer_new.py.
E:\conda\envs\ace_step\lib\site-packages\torch\nn\utils\weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
Traceback (most recent call last):
  File "G:\ACE-Step\trainer_new.py", line 388, in <module>
    main(args)
  File "G:\ACE-Step\trainer_new.py", line 320, in main
    model = Pipeline(
  File "G:\ACE-Step\trainer_new.py", line 81, in __init__
    self.transformer.enable_gradient_checkpointing()
  File "E:\conda\envs\ace_step\lib\site-packages\diffusers\models\modeling_utils.py", line 189, in enable_gradient_checkpointing
    self.apply(partial(self._set_gradient_checkpointing, value=True))
  File "E:\conda\envs\ace_step\lib\site-packages\diffusers\models\modeling_utils.py", line 173, in __getattr__
    return super().__getattr__(name)
  File "E:\conda\envs\ace_step\lib\site-packages\torch\nn\modules\module.py", line 1940, in __getattr__
    raise AttributeError(
AttributeError: 'ACEStepTransformer2DModel' object has no attribute '_set_gradient_checkpointing'. Did you mean: 'is_gradient_checkpointing'?

**Comment by woct0rdho** [comment]
Ok this only works with `diffusers >= 0.33` . I've updated `requirements.txt`
